### ISSUE TITLE
Please remove Android support or update the dependency

### ISSUE THREAD

**Issue by ManuelRauber** [glebosotov/flutter-quick-look#4]
Hi,

I wanted to use your plugin with latest Flutter version and I get this error:

```
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':quick_look' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
```

I'm not sure why you have an empty Android plugin in this project at all. You maybe can remove it and remove it from the plugins supported platforms:

https://github.com/glebosotov/flutter-quick-look/blob/69c8e064bbe805528d67622eab87b8108c4a6dca/pubspec.yaml#L31-L33

**Comment by glebosotov** [comment]
Thanks for the alert, I will check it out

**Comment by ManuelRauber** [comment]
> Thanks for the alert, I will check it out

Great, thank you @glebosotov :)
